# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0007_auto_20170416_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_menu', models.CharField(max_length=40)),
                ('slug_menu', models.CharField(max_length=40)),
                ('type_menu', models.CharField(max_length=40)),
                ('publish', models.BooleanField(default=True)),
                ('id_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('id_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Page')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_menu', models.CharField(max_length=40)),
                ('slug_menu', models.CharField(max_length=40)),
                ('type_menu', models.CharField(max_length=40)),
                ('publish', models.BooleanField(default=True)),
                ('id_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('id_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.MainMenu')),
            ],
        ),
    ]
