# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='slug_menu',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
