# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='logo_web',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
