# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('website', models.CharField(blank=True, max_length=40)),
                ('biodata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('kontributor', 'Kontributor'), ('staff', 'Staff')], max_length=11)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
