# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170416_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biodata',
            field=models.TextField(),
        ),
    ]
