# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 04:08
from __future__ import unicode_literals

from django.db import migrations
#import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170325_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            #field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            #field=tinymce.models.HTMLField(),
        ),
    ]
